encoding: utf-8

title: Welcome! tourist.  
description: Only a bunch of nonsense. 
keywords: Blog 
author: t0ur1s4 
footerText: ''

permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

domainUrl: ''
baseurl: ''

menu:
  - title: Home 
    url: /
  - title: Archive 
    url: /pages/categories.html
  - title: Search 
    url: /pages/search.html
  - title: About 
    url: /pages/about.html

extClickEffect: true

extAdsense: false

extMTA: true

extMath: false

# links:
